function MultiMT_ReplicateRow(hMain, hTbl)

handles = guidata(hMain);
sel_rows = hTbl.SelectedRows;
if isempty(sel_rows)
    return;
end

%% Replication Parameters
num_copies = 1;
ok_pressed = false;
placement = 3; %1='First Row', 2='Before Selection', 3='After Selection', 4='Last Row'

%% make figure
fig_width = 25;
fig_height = 14;
row_height = 2;
txt_offset = 0.5;
txt_height = 1;
row_pos = fig_height-1.25*row_height;

hDlg = figure('Name','Replicate Rows',...
    'units','characters',...
    'Resize','off',...
    'ToolBar','none',...
    'NumberTitle','off',...
    'DockControls','off',...
    'MenuBar','none');

% size figure
pos = get(hDlg,'position');
set(hDlg,'position',[pos(1),pos(2),fig_width,fig_height]);
%movegui(hDlg,'center');

%number of copies
    function editN_callback(hObj,~)
        num = str2double(get(hObj,'string'));
        if ~isnan(num) && num>=0
            num_copies = num;
        end
        set(hObj,'string',num2str(num_copies));
    end


uicontrol('Parent',hDlg,...
            'Style','text',...
            'units','characters',...
            'position',[1,row_pos+txt_offset,15,txt_height],...
            'HorizontalAlignment','left',...
            'String','Number of Copies:');
uicontrol('Parent',hDlg,...
            'Style','edit',...
            'units','characters',...
            'position',[1+15+0.5,row_pos,5,row_height],...
            'HorizontalAlignment','left',...
            'String',num2str(num_copies),...
            'Callback',@editN_callback);
%placement

    function placement_callback(hObj,~)
        placement = get(hObj,'value');
    end

row_pos = row_pos-1*row_height;
uicontrol('Parent',hDlg,...
            'Style','text',...
            'units','characters',...
            'position',[1,row_pos+txt_offset,17,txt_height],...
            'HorizontalAlignment','left',...
            'String','Place Copies:');

row_pos = row_pos-3*row_height;
uicontrol('Parent',hDlg,...
            'Style','listbox',...
            'units','characters',...
            'position',[4,row_pos,17,3*row_height],...
            'HorizontalAlignment','left',...
            'String',{'First Row','Before Selection','After Selection','Last Row'},...
            'Min',0,'Max',1,...%only 1 selection allowed
            'ListboxTop',1,...
            'value',placement,...
            'Callback',@placement_callback);

%ok button
    function ok_callback(~,~)
        ok_pressed = true;
        delete(hDlg);
    end

row_pos = row_pos - 1.25*row_height;
uicontrol('Parent',hDlg,...
            'Style','pushbutton',...
            'units','characters',...
            'position',[fig_width/2-5,row_pos,10,row_height],...
            'HorizontalAlignment','center',...
            'String','OK',...
            'Callback',@ok_callback);
        
%% wait for figure close
waitfor(hDlg);
if ~ok_pressed
    return;
end

%% Replicate selected rows
rep_rows = repmat(handles.ExperimentScheme.ExperimentSteps(sel_rows),1,num_copies);

switch placement
    case 1 %First Row
        handles.ExperimentScheme.ExperimentSteps = ...
        [rep_rows,...
        handles.ExperimentScheme.ExperimentSteps];
    case 2 %Before Selection
        handles.ExperimentScheme.ExperimentSteps = ...
            [handles.ExperimentScheme.ExperimentSteps(1:min(sel_rows)-1),...
            rep_rows,...
            handles.ExperimentScheme.ExperimentSteps(min(sel_rows):end)];
    case 3 %After Selection
        handles.ExperimentScheme.ExperimentSteps = ...
        [handles.ExperimentScheme.ExperimentSteps(1:max(sel_rows)-1),...
            rep_rows,...
            handles.ExperimentScheme.ExperimentSteps(max(sel_rows):end)];
    case 4 %Last Selection
        handles.ExperimentScheme.ExperimentSteps = ...
        [handles.ExperimentScheme.ExperimentSteps,...
        rep_rows];
end

%update table data
MultiMT_ExpUpdateTableData(hTbl,handles.ExperimentScheme);

hTbl.SelectedRows = [];

%Save data
guidata(hMain,handles);
end
