function MultiMTgui_setupMicroscopeControls(hMicroscopeControls)
%Multigui_setupMicroscopeControls Initializes the Microscope control
%window.
% Input:
%   hMicroscopeControls - the handle to the Micrscope control figure
%       This function should be called by the MicroscopeControl figure
%       after the guidata has been updated.
% Example:
%   ...
%   %Update handles structure
%   guidata(hObject,handles);
%   %Setup GUI
%   MultiMTgui_setupMicroscopeControls(hObject);
%
% Note: This function will update the guidata before exiting.

%A handle to the main window is included with this object as hMainWindow

mchandles = guidata(hMicroscopeControls); %get guidata for the Control widow
hMain = mchandles.hMainWindow; %handle to main window
handles = guidata(hMain); %get guidata for the mani window

%Build Camera Controls Panel
set(mchandles.hPnl_CameraControls,'units','characters');
pnl_pos = get(mchandles.hPnl_CameraControls,'position');

bg_color = 'white';%get(0,'defaultUicontrolBackgroundColor');

col_1 = 0.2; %location of labels
width_col_1 = 17; %width of labels
col_2 = 17.6; %location of parameter field

row_height = 2; %height of each row

label_height = 1.4;
label_offset = (row_height-label_height)/2;

slider_height = 1.4;
slider_width = 19;
slider_offset = (row_height-slider_height)/2;

check_height = 2;
check_offset = (row_height-check_height)/2;

edit_height = 1.7;
edit_offset = (row_height-edit_height)/2;

next_row = pnl_pos(4)-1.5-row_height;


%% Capture Rate -- This is how-fast MATLAB can execute the camera liveupdate callback
mchandles.hTxt_CaptureRateLabel = ...
    uicontrol('Parent',mchandles.hPnl_CameraControls,...
    'units','characters',...
    'Style','text',...
    'FontSize',10,...
    'position',[col_1,next_row+label_offset,width_col_1,label_height],...
    'HorizontalAlignment','right',...
    'String','Capture Rate:');
mchandles.hEdt_ActualFrameRate = ...
    uicontrol('Parent',mchandles.hPnl_CameraControls,...
    'BackgroundColor',bg_color,...
    'units','characters',...
    'Style','edit',...
    'FontSize',9,...
    'position',[col_2,next_row+edit_offset,12,edit_height],...
    'HorizontalAlignment','center',...
    'String','XX.XXX',...
    'enable','inactive');
mchandles.hTxt_CaptureRateUnit = ...
    uicontrol('Parent',mchandles.hPnl_CameraControls,...
    'units','characters',...
    'Style','text',...
    'FontSize',8,...
    'position',[col_2+12.5,next_row+label_offset,4,label_height],...
    'HorizontalAlignment','left',...
    'String','Hz');

next_row = next_row-row_height;

%% Frame Rate
if handles.MMcam.bHasFrameRate
    mchandles.hTxt_FrameRateLabel = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'units','characters',...
        'Style','text',...
        'FontSize',10,...
        'position',[col_1,next_row+label_offset,width_col_1,label_height],...
        'HorizontalAlignment','right',...
        'String','Frame Rate:');
    mchandles.hCtrl_FrameRate = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'BackgroundColor',bg_color,...
        'units','characters',...
        'Style','popupmenu',...
        'FontSize',9,...
        'position',[col_2,next_row+edit_offset,12,edit_height],...
        'HorizontalAlignment','center',...
        'String','XX.XX',...
        'callback',@MulitMTgui_FrameRate_Callback);
    col_pos = col_2+12+.5;
    mchandles.hTxt_FrameRateUnit = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'units','characters',...
        'Style','text',...
        'FontSize',8,...
        'position',[col_pos,next_row+label_offset,4,label_height],...
        'HorizontalAlignment','left',...
        'String','Hz');
    col_pos = col_pos+4;
    if isprop(handles.MMcam,'UseFrameRate')
        mchandles.hChk_UseFrameRate = ...
            uicontrol('Parent',mchandles.hPnl_CameraControls,...
                'units','characters',...
                'Style','checkbox',...
                'FontSize',10,...
                'position',[col_pos,next_row+check_offset,10,check_height],...
                'HorizontalAlignment','center',...
                'TooltipString','Limit Frame Rate to specified value',...
                'String','Limit',...
                'enable','on',...
                'Value',handles.MMcam.UseFrameRate,... 
            'callback',@(hObj,~) set(handles.MMcam,'UseFrameRate',hObj.Value));
    end
    
    next_row = next_row-row_height;
    
    %setup frame rate type
    if handles.MMcam.bFrameRateValuesFixed
        set(mchandles.hCtrl_FrameRate,'style','popupmenu');
        set(mchandles.hCtrl_FrameRate,'string',handles.MMcam.csFrameRateValues);
    else
        set(mchandles.hCtrl_FrameRate,'style','edit');
    end
    handles.hCtrl_FrameRate = mchandles.hCtrl_FrameRate;
end

%% Exposure
%all Camera Types have exposure setting (i think this is hardcoded by
%micromanager...)
if true %handles.MMcam.bHasExposure
    mchandles.hTxt_ExposureLabel = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'units','characters',...
        'Style','text',...
        'FontSize',10,...
        'position',[col_1,next_row+label_offset,width_col_1,label_height],...
        'HorizontalAlignment','right',...
        'String','Exposure:');
    mchandles.hEdt_Exposure = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'BackgroundColor',bg_color,...
        'units','characters',...
        'Style','edit',...
        'FontSize',9,...
        'position',[col_2,next_row+edit_offset,10,edit_height],...
        'HorizontalAlignment','center',...
        'String','XX.XXX',...
        'callback',@MulitMTgui_Exposure_Callback);
    mchandles.hTxt_ExposureUnits = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'units','characters',...
        'Style','text',...
        'FontSize',8,...
        'position',[col_2+10.5,next_row+label_offset,3,label_height],...
        'HorizontalAlignment','left',...
        'String',handles.MMcam.sExposureUnits);
    
    handles.hEdt_Exposure = mchandles.hEdt_Exposure;
    
    
    col_pos = col_2+10.5+3+0.5;
    
    if handles.MMcam.bHasExposureLimits
        mchandles.hSld_Exposure = ...
            uicontrol('Parent',mchandles.hPnl_CameraControls,...
            'BackgroundColor',[.9 .9 .9],...
            'units','characters',...
            'Style','slider',...
            'FontSize',10,...
            'position',[col_pos,next_row+slider_offset,slider_width-3,slider_height],...
            'callback',@MulitMTgui_ExposureSlider_Callback);
        handles.MMcam.dExposureLimits
        set(mchandles.hSld_Exposure,'min',handles.MMcam.dExposureLimits(1));
        set(mchandles.hSld_Exposure,'max',handles.MMcam.dExposureLimits(2));
        set(mchandles.hSld_Exposure,'sliderstep',[1,10]/(handles.MMcam.dExposureLimits(2)-handles.MMcam.dExposureLimits(1)));
        
        handles.hSld_Exposure = mchandles.hSld_Exposure;
        
        col_pos = col_pos + slider_width-3+0.2;
    end
    
    if handles.MMcam.bHasExposureAuto
        mchandles.hChk_ExposureAuto = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'units','characters',...
        'Style','checkbox',...
        'FontSize',10,...
        'position',[col_pos,next_row+check_offset,10,check_height],...
        'HorizontalAlignment','center',...
        'String','Auto',...
        'callback',@MulitMTgui_ExposureAuto_Callback);
    handles.hChk_ExposureAuto = mchandles.hChk_ExposureAuto;
    end
    
    next_row = next_row-row_height;
end

%% Gain
if handles.MMcam.bHasGain
   mchandles.hTxt_GainLabel = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'units','characters',...
        'Style','text',...
        'FontSize',10,...
        'position',[col_1,next_row+label_offset,width_col_1,label_height],...
        'HorizontalAlignment','right',...
        'String','Gain:');
    mchandles.hEdt_Gain = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'BackgroundColor',bg_color,...
        'units','characters',...
        'Style','edit',...
        'FontSize',9,...
        'position',[col_2,next_row+edit_offset,5.6,edit_height],...
        'HorizontalAlignment','center',...
        'String','XXX',...
        'callback',@MulitMTgui_Gain_Callback);
    col_pos = col_2+5.6+0.5;
    
    if handles.MMcam.bGainValuesFixed
        set(mchandles.hEdt_Gain,'style','popupmenu');
        set(mchandles.hEdt_Gain,'string',handles.MMcam.csGainValues);
    else
        set(mchandles.hEdt_Gain,'style','edit');
    end
    
    %setup sliders
    if ~any(isnan(handles.MMcam.dGainLimits))
        
        mchandles.hSld_Gain = ...
            uicontrol('Parent',mchandles.hPnl_CameraControls,...
            'BackgroundColor',[.9 .9 .9],...
            'units','characters',...
            'Style','slider',...
            'FontSize',10,...
            'position',[col_pos,next_row+slider_offset,slider_width,slider_height],...
            'callback',@MulitMTgui_GainSlider_Callback);
        
        col_pos = col_pos+slider_width+0.5;
        
        set(mchandles.hSld_Gain,'min',handles.MMcam.dGainLimits(1));
        set(mchandles.hSld_Gain,'max',handles.MMcam.dGainLimits(2));
        set(mchandles.hSld_Gain,'sliderstep',[1,10]/(handles.MMcam.dGainLimits(2)-handles.MMcam.dGainLimits(1)));
        
        handles.hSld_Gain = mchandles.hSld_Gain;
    end
    handles.hEdt_Gain = mchandles.hEdt_Gain;
        
    if handles.MMcam.bHasGainAuto
       mchandles.hChk_GainAuto = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'units','characters',...
        'Style','checkbox',...
        'FontSize',10,...
        'position',[col_pos,next_row+check_offset,10,check_height],...
        'HorizontalAlignment','center',...
        'String','Auto',...
        'callback',@MulitMTgui_GainAuto_Callback);
    handles.hChk_GainAuto = mchandles.hChk_GainAuto;
    end
    
    next_row = next_row-row_height;
end

%% Soft AutoGain
if handles.MMcam.bHasSoftAutoGain
    mchandles.hTxt_SoftAutoGainLabel = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'units','characters',...
        'Style','text',...
        'FontSize',10,...
        'position',[col_1,next_row+label_offset,width_col_1,label_height],...
        'HorizontalAlignment','right',...
        'TooltipString','Software Autogain',...
        'String','Autogain:');
    mchandles.hEdt_SoftAutoGain = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'BackgroundColor',bg_color,...
        'units','characters',...
        'Style','edit',...
        'FontSize',9,...
        'position',[col_2,next_row+edit_offset,5.6,edit_height],...
        'HorizontalAlignment','center',...
        'String','XXX',...
        'TooltipString','Set Target Average Intensity',...
        'callback',@MulitMTgui_SoftAutoGain_Callback);
    col_pos = col_2+5.6+0.5;
    handles.hEdt_SoftAutoGain = mchandles.hEdt_SoftAutoGain;
    
    %setup sliders
    if ~any(isnan(handles.MMcam.SoftAutoGainLimits))
        
        mchandles.hSld_SoftAutoGain = ...
            uicontrol('Parent',mchandles.hPnl_CameraControls,...
            'BackgroundColor',[.9 .9 .9],...
            'units','characters',...
            'Style','slider',...
            'TooltipString','Set Target Average Intensity',...
            'FontSize',10,...
            'position',[col_pos,next_row+slider_offset,slider_width,slider_height],...
            'callback',@MulitMTgui_SoftAutoGainSlider_Callback);
        
        col_pos = col_pos+slider_width+0.5;
        
        set(mchandles.hSld_SoftAutoGain,'min',handles.MMcam.SoftAutoGainLimits(1));
        set(mchandles.hSld_SoftAutoGain,'max',handles.MMcam.SoftAutoGainLimits(2));
        set(mchandles.hSld_Gain,'sliderstep',[0.01,0.1]);
        
        handles.hSld_SoftAutoGain = mchandles.hSld_SoftAutoGain;
    end
    
    mchandles.hChk_SoftAutoGain = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'units','characters',...
        'Style','checkbox',...
        'FontSize',10,...
        'TooltipString','Enable/Disable Software Autogain',...
        'position',[col_pos,next_row+check_offset,2.8,check_height],...
        'HorizontalAlignment','center',...
        'String','',...
        'callback',@MulitMTgui_SoftAutoGainCheckbox_Callback);
    handles.hChk_SoftAutoGain = mchandles.hChk_SoftAutoGain;
    col_pos = col_pos+2.8+0.6;
    
    mchandles.hEdt_SoftAutoGainIntensity = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'BackgroundColor',bg_color,...
        'units','characters',...
        'Style','text',...
        'FontSize',7.5,...
        'position',[col_pos,next_row+label_offset,5.7,label_height],...
        'TooltipString','Current Average Intensity',...
        'HorizontalAlignment','center',...
        'String','XXX');
    handles.hEdt_SoftAutoGainIntensity = mchandles.hEdt_SoftAutoGainIntensity;

    next_row = next_row-row_height;
end

%% Brightness
if handles.MMcam.bHasBrightness
   mchandles.hTxt_BrightnessLabel = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'units','characters',...
        'Style','text',...
        'FontSize',10,...
        'position',[col_1,next_row+label_offset,width_col_1,label_height],...
        'HorizontalAlignment','right',...
        'String','Brightness:');
    mchandles.hEdt_Brightness = ...
        uicontrol('Parent',mchandles.hPnl_CameraControls,...
        'BackgroundColor',bg_color,...
        'units','characters',...
        'Style','edit',...
        'FontSize',9,...
        'position',[col_2,next_row+edit_offset,5.6,edit_height],...
        'HorizontalAlignment','center',...
        'String','XXX',...
        'callback',@MulitMTgui_Brightness_Callback);
    col_pos = col_2+5.6+0.5;
    
    if handles.MMcam.bBrightnessValuesFixed
        set(mchandles.hEdt_Brightness,'style','popupmenu');
        set(mchandles.hEdt_Brightness,'string',handles.MMcam.csBrightnessValues);
    else
        set(mchandles.hEdt_Brightness,'style','edit');
    end
    handles.hEdt_Brightness = mchandles.hEdt_Brightness;
    %setup sliders
    if ~any(isnan(handles.MMcam.dBrightnessLimits))
        
        mchandles.hSld_Brightness = ...
            uicontrol('Parent',mchandles.hPnl_CameraControls,...
            'BackgroundColor',[.9 .9 .9],...
            'units','characters',...
            'Style','slider',...
            'FontSize',10,...
            'position',[col_pos,next_row+slider_offset,slider_width,slider_height],...
            'callback',@MulitMTgui_BrightnessSlider_Callback);
        
        col_pos = col_pos+slider_width+0.5;
        
        set(mchandles.hSld_Brightness,'min',handles.MMcam.dBrightnessLimits(1));
        set(mchandles.hSld_Brightness,'max',handles.MMcam.dBrightnessLimits(2));
        set(mchandles.hSld_Brightness,'sliderstep',[1,10]/(handles.MMcam.dBrightnessLimits(2)-handles.MMcam.dBrightnessLimits(1)));
        
        handles.hSld_Brightness = mchandles.hSld_Brightness;
    end
        
%     if handles.MMcam.bHasBrightnessAuto
%        mchandles.hChk_BrightnessAuto = ...
%         uicontrol('Parent',mchandles.hPnl_CameraControls,...
%         'Style','checkbox',...
%         'FontSize',10,...
%         'position',[col_pos,next_row+check_offset,10,check_height],...
%         'HorizontalAlignment','right',...
%         'String','Auto'); 
%     end
    
    next_row = next_row-row_height;
end

%% ROI
if handles.MMcam.HasROI
    next_row = next_row - 4.5*row_height;
    set(mchandles.hPnl_CameraControls,'units','characters');
    par_pos = get(mchandles.hPnl_CameraControls,'position');
    [mchandles.hPnl_ROI, mchandles.hChk_UseROI] = ...
        uipanel_checkbox('Parent',mchandles.hPnl_CameraControls,...
            'units','characters',...
            'position',[0.2,next_row,par_pos(3)-.4,4*row_height],...
            'Callback',@MulitMTgui_UseROI_Callback,...
            'UseListener',false,...
            'FontSize',10,...
            'Title','ROI',...
            'Value',true);

    %create ROI control elements in panel
    pnl_pos = get(mchandles.hPnl_ROI,'position');
    ROI_row = pnl_pos(4)-2*row_height;
    ROI_col1 = 0.2;
    col = ROI_col1;
    %% width
    mchandles.hTxt_ROIwidthlabel = ...
        uicontrol('Parent',mchandles.hPnl_ROI,...
        'units','characters',...
        'Style','text',...
        'FontSize',10,...
        'position',[col,ROI_row+label_offset,11,label_height],...
        'HorizontalAlignment','right',...
        'String','Width:');
    col = col + 11.2;
    mchandles.hEdt_ROIWidth = ...
        uicontrol('Parent',mchandles.hPnl_ROI,...
        'units','characters',...
        'Style','edit',...
        'FontSize',10,...
        'position',[col,ROI_row+edit_offset,8,edit_height],...
        'HorizontalAlignment','center',...
        'String','XXXX',...
        'Callback',@MulitMTgui_ROIWidth_Callback);
    %% X
    col = col + 8.5;
    mchandles.hTxt_ROIxlabel = ...
        uicontrol('Parent',mchandles.hPnl_ROI,...
        'units','characters',...
        'Style','text',...
        'FontSize',10,...
        'position',[col,ROI_row+label_offset,3,label_height],...
        'HorizontalAlignment','right',...
        'String','X:');
    col = col+3.1;
    mchandles.hEdt_ROIOffsetX = ...
        uicontrol('Parent',mchandles.hPnl_ROI,...
        'units','characters',...
        'Style','edit',...
        'FontSize',10,...
        'position',[col,ROI_row+edit_offset,8,edit_height],...
        'HorizontalAlignment','center',...
        'String','XXXX',...
        'Callback',@MulitMTgui_ROIOffsetX_Callback);
    col=col+8.1;
%     mchandles.hChk_ROICenterX = ...
%     uicontrol('Parent',mchandles.hPnl_ROI,...
%         'units','characters',...
%         'Style','checkbox',...
%         'FontSize',10,...
%         'TooltipString','Center ROI in X',...
%         'position',[col,ROI_row+check_offset,16,check_height],...
%         'HorizontalAlignment','left',...
%         'String','Center',...
%         'callback',@MulitMTgui_ROICenterX_Callback);
    %% height
    ROI_row = ROI_row - row_height;
    col = ROI_col1;
    mchandles.hTxt_ROIheightlabel = ...
        uicontrol('Parent',mchandles.hPnl_ROI,...
        'units','characters',...
        'Style','text',...
        'FontSize',10,...
        'position',[col,ROI_row+label_offset,11,label_height],...
        'HorizontalAlignment','right',...
        'String','Height:');
    col = col + 11.2;
    mchandles.hEdt_ROIHeight = ...
        uicontrol('Parent',mchandles.hPnl_ROI,...
        'units','characters',...
        'Style','edit',...
        'FontSize',10,...
        'position',[col,ROI_row+edit_offset,8,edit_height],...
        'HorizontalAlignment','center',...
        'String','XXXX',...
        'Callback',@MulitMTgui_ROIHeight_Callback);
    col = col + 8.5;
    %% Y
    mchandles.hTxt_ROIylabel = ...
        uicontrol('Parent',mchandles.hPnl_ROI,...
        'units','characters',...
        'Style','text',...
        'FontSize',10,...
        'position',[col,ROI_row+label_offset,3,label_height],...
        'HorizontalAlignment','right',...
        'String','Y:');
    col = col+3.1;
    mchandles.hEdt_ROIOffsetY = ...
        uicontrol('Parent',mchandles.hPnl_ROI,...
        'units','characters',...
        'Style','edit',...
        'FontSize',10,...
        'position',[col,ROI_row+edit_offset,8,edit_height],...
        'HorizontalAlignment','center',...
        'String','XXXX',...
        'Callback',@MulitMTgui_ROIOffsetY_Callback);
    col=col+8.1;
%     mchandles.hChk_ROICenterY = ...
%     uicontrol('Parent',mchandles.hPnl_ROI,...
%         'units','characters',...
%         'Style','checkbox',...
%         'FontSize',10,...
%         'TooltipString','Center ROI in Y',...
%         'position',[col,ROI_row+check_offset,16,check_height],...
%         'HorizontalAlignment','left',...
%         'String','Center',...
%         'callback',@MulitMTgui_ROICenterY_Callback);
    %% ROI Buttons
    ROI_row = ROI_row - row_height;
    btn_w = pnl_pos(3)/2-2;
    col = 1.5;
    mchandles.hBtn_ROIsetROI = ...
        uicontrol('Parent',mchandles.hPnl_ROI,...
        'units','characters',...
        'style','pushbutton',...
        'FontSize',10,...
        'ToolTipString','Select ROI using cursor',...
        'position',[col,ROI_row+edit_offset,btn_w,edit_height],...
        'HorizontalAlignment','center',...
        'String','Set ROI',...
        'callback',@MultiMTgui_ROIsetROI);
    col = col+btn_w+.5;
    mchandles.hBtn_ROIclearROI = ...
        uicontrol('Parent',mchandles.hPnl_ROI,...
        'units','characters',...
        'style','pushbutton',...
        'FontSize',10,...
        'ToolTipString','Clear ROI',...
        'position',[col,ROI_row+edit_offset,btn_w,edit_height],...
        'HorizontalAlignment','center',...
        'String','Clear ROI',...
        'callback',@MultiMTgui_ROIclearROI);
    
    set(mchandles.hChk_UseROI,'value',handles.MMcam.UsingROI);
    drawnow;
end

%% Break out all the microscope control elements to the main handles variable
handles.hFig_MicroscopeControls = hMicroscopeControls;

%% Objective and Motor Controls
if strcmpi('electromagnet', handles.MotorController)
    %set(mchandles.hPnl_MotorControls, 'Visible', 'off');
    set(mchandles.hPnl_MagRot, "Visible", 'off');
end
handles.hSld_ObjectiveHeight = mchandles.hSld_ObjectiveHeight;
handles.hEdt_ObjectiveHeight = mchandles.hEdt_ObjectiveHeight;
handles.hTxt_ObjectiveRangeMax = mchandles.hTxt_ObjectiveRangeMax;
handles.hTxt_ObjectiveRangeMin = mchandles.hTxt_ObjectiveRangeMin;
handles.hEdt_MagnetHeight = mchandles.hEdt_MagnetHeight;
handles.hSld_MagnetHeight = mchandles.hSld_MagnetHeight;
handles.hTxt_MagnetHeightMax = mchandles.hTxt_MagnetHeightMax;
handles.hTxt_MagnetHeightMin = mchandles.hTxt_MagnetHeightMin;
handles.hEdt_MagnetHeightSpeed = mchandles.hEdt_MagnetHeightSpeed;
handles.hEdt_MagnetRotation = mchandles.hEdt_MagnetRotation;
handles.hEdt_MagnetRotationSpeed = mchandles.hEdt_MagnetRotationSpeed;
%handles.hBtn_StopMotor = mchandles.hBtn_StopMotor;
handles.hEdt_ActualFrameRate = mchandles.hEdt_ActualFrameRate;

handles.hEdt_ActualObjectiveHeight = mchandles.hEdt_ActualObjectiveHeight;
%Set control initialized flag
handles.controls_open = true;

guidata(hMain,handles); %save gui data for calling functions

getCameraBrightness(hMain);
getCameraExposure(hMain);
getCameraExposureAuto(hMain);
getCameraFrameRate(hMain);
getCameraGain(hMain);
getCameraGainAuto(hMain);


getCameraSoftAutoGainIntensity(hMain);
getCameraSoftAutoGainEnable(hMain);
getCameraSoftAutoGainCurrentIntensity(hMain);


handles = guidata(hMain); %get guidata because calling functions update the handles


%setup hardware
%setup slider limits
set(handles.hSld_ObjectiveHeight,'min',handles.obj_zlim(1));
set(handles.hSld_ObjectiveHeight,'max',handles.obj_zlim(2));
set(handles.hSld_ObjectiveHeight,'sliderstep',[0.1,1]/(handles.obj_zlim(2)-handles.obj_zlim(1)) );

set(handles.hTxt_ObjectiveRangeMax,'string',num2str(handles.obj_zlim(2),'%0.0f'));
set(handles.hTxt_ObjectiveRangeMin,'string',num2str(handles.obj_zlim(1),'%0.0f'));

%setup slider limits

set(handles.hSld_MagnetHeight,'min',handles.mag_zlim(1));
set(handles.hSld_MagnetHeight,'max',handles.mag_zlim(2));
set(handles.hSld_MagnetHeight,'sliderstep',[.1,1]/(handles.mag_zlim(2)-handles.mag_zlim(1)));

set(handles.hTxt_MagnetHeightMax,'string',num2str(handles.mag_zlim(2),'%0.0f'));
set(handles.hTxt_MagnetHeightMin,'string',num2str(handles.mag_zlim(1),'%0.0f'));                             

%% SAVE THE GUI DATA
guidata(hMain,handles);
guidata(hMicroscopeControls,mchandles);

getMagnetRotation(hMain);
getMagnetRotSpeed(hMain);
getMagnetZPosition(hMain);
getMagnetZSpeed(hMain);
getObjectivePosition(hMain);
getActualObjectivePosition(hMain);
updateHardwareInfo(hMain);
  
%run updatecallback
MultiMTgui_CameraPropertiesUpdateCallback(handles.MMcam,hMain);
end

